# Generated by Django 6.1 on 2026-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bookrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
